[package]
name = "wordsolve"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true

[dependencies]
clap = { version = "3.0", features = ["derive"] }
fxhash = "0.2"
float-ord = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
static_assertions = "1.1"
