all:

deploy: dist/.git/config all
	wasm-pack build --release --target=no-modules
	rsync -Rar --delete index.html script.js style.css worker.js pkg/wordsolve.js pkg/wordsolve_bg.wasm dist/

	cd $(<D)/.. && \
	git add -A && \
	git commit --amend -q -m Autogenerated && \
	git push -f origin gh-pages

dist/.git/config:
	mkdir -p $(@D)
	url=`git remote -v | grep origin | awk '{ printf "%s", $$2; exit }'` && \
	cd $(@D)/.. && \
	git init -b gh-pages && \
	git config user.name Bot && \
	git config user.email "<>" && \
	git commit -m _ --allow-empty && \
	git remote add origin "$$url"
